### ISSUE TITLE
スプリントミーティングの流れをまとめる

### ISSUE THREAD

**Issue by bouru02** [brutex/ranking-memo#33]
## 目的
スプリングミーティングが滞りなく進むように

## ゴール
Wikiに記述

**Comment by bouru02** [comment]
議事録って来週からはGoogleドキュメントにまとめることになったんだっけ？

**Comment by bbbbruno** [comment]
@bouru02 
はい、そのつもりです。
まだ前回のやつGoogleドキュメントに移せてなくてすみません。。
土日中に移しておきます！！

**Comment by bouru02** [comment]
@bbbbruno 
了解！ドキュメントへのリンクはどこで共有しようか？
Wikiにまとめ作って毎週張ってきます？

**Comment by bouru02** [comment]
MTGの流れこんな感じかな？
1. 先週のIssueの進捗確認
2. IssueについてのFB
3. その他気になったことについて
4. 今週のIssueの共有

なにか足りなそうだからアイデアあればちょうだいな

**Comment by bbbbruno** [comment]
@bouru02 
流れについては大体それでいいと思います。
やっていくうちに調整していきましょう。

ドキュメントについてはhack.mdっていうやつを使うことにしました↓
https://hackmd.io/team/brutex
詳しくはMTGで話します
